const Map<String, String> en = {
  "Search": "البحث",
  "Sign In": "Sign In ",
  "Connect with us": "Connect with us",
  "Rate Us": "Rate Us",
  "Privacy policy": "Privacy policy",
  "Terms & Conditions": "Terms & Conditions",
  "Common questions": "Common questions",
  "Favorite": "Favorite",
  "Add a discount code": "Add a discount code",
  "Store details": "Store details",
  "Store name": "Store name",
  "Store Link(optianl)": "Store Link(optianl)",
  "Upload Logo": "Upload Logo",
  "Jpg": "Try uploading a square dimension logo (SVG او PNG , JPEG )",
  "Discount Details": "Discount Details",
  "Type:": "Type",
  "offer": "offer",
  "copuon": "copuon",
  "Countries": "Countries",
  "Link offer": "Link offer",
  "Copun code": "Copun code",
  "Start Date": "Start Date",
  "End Date": "End Date",
  "Date is not selected": "Date is not selected",
  " Descreotion(optional)": " Descreotion(optional)",
  "Addition Terms": "Addition Terms",
  "e-shop": "- It must be e-shop",
  "valid": "- The discount code is valid",
  "frequent": "- If the e-shop is frequent, the offer should be different",
  "Add": "Add",
  "Required": "Required",
  "CANCEL": "CANCEL",
  "Ok": "Ok",
  "Stores": "Stores",
  "Home": "Home",
  "Menu": "Menu",
  "Last Valid use:": "آخر استخدام صالح:",
  'Vaild': "vaild",
  "invalid": "invalid",
  "Derails": "Derails",
  "offers": "offer",
  "show now": "show now",
  "Login": "Login",
  "Email": "Email",
  "password": "Password",
  "Forget Your passwor?": "Forget Your passwor?",
  "New User ? ": "New User ?",
  "Sign Up": "Sign Up",
  "UserName": "UserName",
  "Done": "Done",
  "Add Copoun": "Add Copoun",
  "logout": "Logout",
  "Sorry": "Sorry",
  "Content": "You can only add your coupon when you log in.",
};
